// Generated by Wrangler on Mon Jun 03 2024 14:30:07 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_CLOUD_CREDENTIALS: string;
	SPREADSHEET_ID: string;
	DB: D1Database;
	QUEUE: Queue;
}
